### ISSUE TITLE
Packages for the project

### ISSUE THREAD

**Issue by 0tieno** [0tieno/techiesConnectPlatform#15]

**Comment by 0tieno** [comment]
I suggest we use react-router and material UI just to get us started. Though I haven't worked with Material UI before but it's something I can learn as we work on the project. You can suggest some more. @KingKiarie

**Comment by KingKiarie** [comment]
I have curated a list of the packages we may need in the discussion panel. I choose Mui, React-router-dom, the backend packages and  axios

**Comment by 0tieno** [comment]
I have seen it. There Must be a lot to learn along the way 🤣

**Comment by KingKiarie** [comment]
you have no idea LOL
