### ISSUE TITLE
4th branch

### ISSUE THREAD

**Issue by KingKiarie** [0tieno/techiesConnectPlatform#19]
folder structure

**Comment by 0tieno** [comment]
> folder structure

what about it?

**Comment by KingKiarie** [comment]
I feel as though the client folder should cover the entire frontend files then we can have a server for the backend.
|-Client
   |-frontend files
|-server
   |-Backend files

**Comment by 0tieno** [comment]
Alright, I get the sense. So two main folders? could you do a PR I see it.

**Comment by KingKiarie** [comment]
techies-connect-hub/
│
├── client/                 # Frontend React Application
│   ├── public/             # Public assets (index.html, favicon.ico, etc.)
│   └── src/                # Source code
│       ├── components/     # React components
│       ├── pages/          # Page components
│       ├── utils/          # Utility functions
│       ├── App.js          # Main React App component
│       ├── index.js        # Entry point for React app
│       └── ...             # Other configuration files
│
├── server/                 # Backend Node.js Application
│   ├── controllers/        # Controllers for handling routes
│   ├── models/             # Mongoose models for MongoDB
│   ├── routes/             # Express routes
│   ├── config/             # Configuration files (database, environment, etc.)
│   ├── middleware/         # Custom middleware
│   ├── services/           # Business logic services
│   ├── app.js              # Express application setup
│   └── ...                 # Other configuration files
│
├── node_modules/           # Node.js modules (generated)
├── package.json            # Node.js dependencies and project information
├── package-lock.json       # Lock file for Node.js dependencies
├── .gitignore              # Files and folders to ignore in version control
└── README.md               # Project documentation

**Comment by 0tieno** [comment]
could you do a PR for that

**Comment by KingKiarie** [comment]
The file structure is good
