### ISSUE TITLE
Design Wireframes and UI Mockups

### ISSUE THREAD

**Issue by 0tieno** [0tieno/techiesConnectPlatform#7]
Hey, @KingKiarie I have seen up to where you have reached with the Design Wireframes and UI mockup for our project. I now think you will conclude this week `sprint 1`. Do you think we can have a Google Meet in the week to talk about it?

**Comment by KingKiarie** [comment]
I have embed the link for the FIGMA homepage prototype. I shall gradually add mockups to the other pages over the weekend.

**Comment by 0tieno** [comment]
Okay, fine @KingKiarie I have seen the good work. I will review it tomorrow before our meeting and then merge it.

> I have embedded the link for the FIGMA homepage prototype. I shall gradually add mockups to the other pages over the weekend.

**Comment by KingKiarie** [comment]
updated
